version: "3"

services:
  flaskt:
    image: web-flaskt:latest
    container_name: flaskt
    build: ./flaskt
    environment:
      - TZ=Asia/Shanghai
    volumes:
    - ./flaskt:/code
    - /home/dockerdata/log/gun:/var/log/gun
    - /home/dockerdata/log/flaskt:/var/log/flaskt

  nginx:
    image: nginx-flaskt:latest
    container_name: nginx-flaskt
    build: nginx/.
    ports:
      - "80:80"
    depends_on:
      - flaskt
    environment:
      - TZ=Asia/Shanghai
    volumes:
     - /home/dockerdata/log/nginx:/var/log/nginx

  redis-master:
    image: redis:latest
    container_name: redis-master
    ports: 
     - "8001:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
     - TZ=Asia/Shanghai
    volumes:
     - /home/dockerdata/redis/8001:/data
     - ./redis/redis-master.conf:/usr/local/etc/redis/redis.conf
    networks:
     - sentinel-master

  redis-slave-1:
    image: redis:latest
    container_name: redis-slave-1
    ports: 
      - "8002:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    volumes:
     - /home/dockerdata/redis/8002:/data
     - ./redis/redis-slave-1.conf:/usr/local/etc/redis/redis.conf
    depends_on: 
      - redis-master
    networks:
     - sentinel-master

  redis-slave-2:
    image: redis:latest
    container_name: redis-slave-2
    ports: 
      - "8003:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    volumes:
     - /home/dockerdata/redis/8003:/data
     - ./redis/redis-slave-2.conf:/usr/local/etc/redis/redis.conf
    depends_on: 
      - redis-master
    networks:
     - sentinel-master

  redis-sentinel-1:
    image: redis:latest
    container_name: redis-sentinel-1
    ports:
      - "18000:16379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./redis/redis-sentinel-1.conf:/usr/local/etc/redis/sentinel.conf"
    depends_on: 
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
     - sentinel-master

  redis-sentinel-2:
    image: redis:latest
    container_name: redis-sentinel-2
    ports:
      - "18001:16379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./redis/redis-sentinel-2.conf:/usr/local/etc/redis/sentinel.conf"
    depends_on: 
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
     - sentinel-master

  redis-sentinel-3:
    image: redis:latest
    container_name: redis-sentinel-3
    ports:
      - "18002:16379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./redis/redis-sentinel-3.conf:/usr/local/etc/redis/sentinel.conf"
    depends_on: 
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
     - sentinel-master

networks:
  sentinel-master:
