version: "3"

services:
  flaskt:
    container_name: flaskt
    build: ./flaskt
    environment:
      - TZ=Asia/Shanghai
    volumes:
    - ./flaskt:/code
    - ./log/gun:/var/log/gun
    - ./log/flaskt:/var/log/flaskt

  nginx:
    container_name: nginx-flaskt
    build: nginx/.
    ports:
      - "80:80"
    depends_on:
      - flaskt
    environment:
      - TZ=Asia/Shanghai
    volumes:
     - ./log/nginx:/var/log/nginx
