version: "3"

services:
  hunger:
    image: web-hunger:latest
    container_name: hunger
    build: ./hunger
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./hunger:/code
      - ./dockerdata/log/gun:/var/log/gun
      - ./dockerdata/log/hunger:/var/log/hunger
    depends_on:
      - redis-sentinel-1
      - redis-sentinel-2
      - redis-sentinel-3
    restart: always
    networks:
      sentinel-master:
        ipv4_address: 172.20.1.10

  nginx:
    image: nginx-hunger:latest
    container_name: nginx-hunger
    build: nginx/.
    ports:
      - "80:80"
    depends_on:
      - hunger
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./dockerdata/log/nginx:/var/log/nginx
    restart: always
    networks:
      sentinel-master:
        ipv4_address: 172.20.2.10

  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "7001:6379"
    command: bash -c "
      cp -fp /usr/local/etc/redis/redis-master.conf /data/redis.conf
      && redis-server /data/redis.conf"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./dockerdata/redis/redis-master:/data
      - ./redis/redis-master:/usr/local/etc/redis
    networks:
      sentinel-master:
        ipv4_address: 172.20.3.10

  redis-slave-1:
    image: redis:latest
    container_name: redis-slave-1
    ports:
      - "7002:6379"
    command: bash -c "
      cp -fp /usr/local/etc/redis/redis-slave-1.conf /data/redis.conf
      && redis-server /data/redis.conf"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./dockerdata/redis/redis-slave-1:/data
      - ./redis/redis-slave-1:/usr/local/etc/redis
    depends_on:
      - redis-master
    networks:
      sentinel-master:
        ipv4_address: 172.20.3.11

  redis-slave-2:
    image: redis:latest
    container_name: redis-slave-2
    ports:
      - "7003:6379"
    command: bash -c "
      cp -fp /usr/local/etc/redis/redis-slave-2.conf /data/redis.conf
      && redis-server /data/redis.conf"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./dockerdata/redis/redis-slave-2:/data
      - ./redis/redis-slave-2:/usr/local/etc/redis
    depends_on:
      - redis-master
    networks:
      sentinel-master:
        ipv4_address: 172.20.3.12

  redis-sentinel-1:
    image: redis:latest
    container_name: redis-sentinel-1
    ports:
      - "17001:16379"
    command: bash -c "
      cp -fp /usr/local/etc/redis/redis-sentinel-1.conf /data/sentinel.conf
      && redis-sentinel /data/sentinel.conf"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./dockerdata/redis/redis-sentinel-1:/data
      - ./redis/redis-sentinel-1:/usr/local/etc/redis
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      sentinel-master:
        ipv4_address: 172.20.4.10

  redis-sentinel-2:
    image: redis:latest
    container_name: redis-sentinel-2
    ports:
      - "17002:16379"
    command: bash -c "
      cp -fp /usr/local/etc/redis/redis-sentinel-2.conf /data/sentinel.conf
      && redis-sentinel /data/sentinel.conf"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./dockerdata/redis/redis-sentinel-2:/data
      - ./redis/redis-sentinel-2:/usr/local/etc/redis
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      sentinel-master:
        ipv4_address: 172.20.4.11

  redis-sentinel-3:
    image: redis:latest
    container_name: redis-sentinel-3
    ports:
      - "17003:16379"
    command: bash -c "
      cp -fp /usr/local/etc/redis/redis-sentinel-3.conf /data/sentinel.conf
      && redis-sentinel /data/sentinel.conf"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./dockerdata/redis/redis-sentinel-3:/data
      - ./redis/redis-sentinel-3:/usr/local/etc/redis
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      sentinel-master:
        ipv4_address: 172.20.4.12

networks:
  sentinel-master:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

