version: "3"

services:
  flaskt:
    image: web-flaskt:latest
    container_name: flaskt
    build: ./flaskt
    environment:
      - TZ=Asia/Shanghai
    volumes:
    - ./flaskt:/code
    - /home/dockerdata/log/gun:/var/log/gun
    - /home/dockerdata/log/flaskt:/var/log/flaskt
    depends_on: 
      - redis-sentinel-1
      - redis-sentinel-2
      - redis-sentinel-3
    networks:
      sentinel-master:
        ipv4_address: 172.20.1.10
     
  nginx:
    image: nginx-flaskt:latest
    container_name: nginx-flaskt
    build: nginx/.
    ports:
      - "80:80"
    depends_on:
      - flaskt
    environment:
      - TZ=Asia/Shanghai
    volumes:
     - /home/dockerdata/log/nginx:/var/log/nginx
    networks:
      sentinel-master:
        ipv4_address: 172.20.2.10

  redis-master:
    image: redis:latest
    container_name: redis-master
    ports: 
     - "8001:6379"
    command: bash -c "
      cp -fp /usr/local/etc/redis/redis-master.conf /data/redis.conf
      && redis-server /data/redis.conf"
    environment:
     - TZ=Asia/Shanghai
    volumes:
     - /home/dockerdata/redis/redis-master:/data
     - ./redis/redis-master:/usr/local/etc/redis
    networks:
      sentinel-master:
        ipv4_address: 172.20.3.10
  
  redis-slave-1:
    image: redis:latest
    container_name: redis-slave-1
    ports: 
      - "8002:6379"
    command: bash -c "
      cp -fp /usr/local/etc/redis/redis-slave-1.conf /data/redis.conf
      && redis-server /data/redis.conf"
    environment:
      - TZ=Asia/Shanghai
    volumes:
     - /home/dockerdata/redis/redis-slave-1:/data
     - ./redis/redis-slave-1:/usr/local/etc/redis
    depends_on: 
      - redis-master
    networks:
      sentinel-master:
        ipv4_address: 172.20.3.11

  redis-slave-2:
    image: redis:latest
    container_name: redis-slave-2
    ports: 
      - "8003:6379"
    command: bash -c "
      cp -fp /usr/local/etc/redis/redis-slave-2.conf /data/redis.conf
      && redis-server /data/redis.conf"
    environment:
      - TZ=Asia/Shanghai
    volumes:
     - /home/dockerdata/redis/redis-slave-2:/data
     - ./redis/redis-slave-2:/usr/local/etc/redis
    depends_on: 
      - redis-master
    networks:
      sentinel-master:
        ipv4_address: 172.20.3.12

  redis-sentinel-1:
    image: redis:latest
    container_name: redis-sentinel-1
    ports:
      - "18001:16379"
    command: bash -c "
      cp -fp /usr/local/etc/redis/redis-sentinel-1.conf /data/sentinel.conf
      && redis-sentinel /data/sentinel.conf"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/dockerdata/redis/redis-sentinel-1:/data
      - ./redis/redis-sentinel-1:/usr/local/etc/redis
    depends_on: 
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      sentinel-master:
        ipv4_address: 172.20.4.10

  redis-sentinel-2:
    image: redis:latest
    container_name: redis-sentinel-2
    ports:
      - "18002:16379"
    command: bash -c "
      cp -fp /usr/local/etc/redis/redis-sentinel-2.conf /data/sentinel.conf
      && redis-sentinel /data/sentinel.conf"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/dockerdata/redis/redis-sentinel-2:/data
      - ./redis/redis-sentinel-2:/usr/local/etc/redis
    depends_on: 
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      sentinel-master:
        ipv4_address: 172.20.4.11

  redis-sentinel-3:
    image: redis:latest
    container_name: redis-sentinel-3
    ports:
      - "18003:16379"
    command: bash -c "
      cp -fp /usr/local/etc/redis/redis-sentinel-3.conf /data/sentinel.conf
      && redis-sentinel /data/sentinel.conf"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/dockerdata/redis/redis-sentinel-3:/data
      - ./redis/redis-sentinel-3:/usr/local/etc/redis
    depends_on: 
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      sentinel-master:
        ipv4_address: 172.20.4.12

networks:
  sentinel-master:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

